# 기반

In [0]:
import csv
import numpy as np
import pandas as pd

In [3]:
!wget https://raw.githubusercontent.com/dhrim/cup_deeplearning_seminar/master/%EA%B5%90%EC%9C%A1%EC%9E%90%EB%A3%8C/deep_learning/iris.csv

--2019-07-21 14:46:11--  https://raw.githubusercontent.com/dhrim/cup_deeplearning_seminar/master/%EA%B5%90%EC%9C%A1%EC%9E%90%EB%A3%8C/deep_learning/iris.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2720 (2.7K) [text/plain]
Saving to: ‘iris.csv’

iris.csv            100%[===================>]   2.66K  --.-KB/s    in 0s      

2019-07-21 14:46:11 (54.8 MB/s) - ‘iris.csv’ saved [2720/2720]



In [4]:
iris = pd.read_csv("iris.csv")
iris.head()

septal_length  septal_width  petal_length  ...  setosa  versicolor  virginica
0            6.4           2.8           5.6  ...       0           0          1
1            5.0           2.3           3.3  ...       0           1          0
2            4.9           2.5           4.5  ...       0           0          1
3            4.9           3.1           1.5  ...       1           0          0
4            5.7           3.8           1.7  ...       1           0          0

[5 rows x 7 columns]

In [5]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
septal_length    120 non-null float64
septal_width     120 non-null float64
petal_length     120 non-null float64
petal_width      120 non-null float64
setosa           120 non-null int64
versicolor       120 non-null int64
virginica        120 non-null int64
dtypes: float64(4), int64(3)
memory usage: 6.6 KB


In [7]:
data = iris.to_numpy()
print(data.shape)
print(data[:5])

(120, 7)
[[6.4 2.8 5.6 2.2 0.  0.  1. ]
 [5.  2.3 3.3 1.  0.  1.  0. ]
 [4.9 2.5 4.5 1.7 0.  0.  1. ]
 [4.9 3.1 1.5 0.1 1.  0.  0. ]
 [5.7 3.8 1.7 0.3 1.  0.  0. ]]


In [8]:
train, test = data[:100], data[100:]
print(train.shape)
print(test.shape)

train_input, train_output = train[:,:4], train[:,4:]
test_input, test_output = test[:,:4], test[:,4:]

print(train_input.shape)
print(train_output.shape)

print(test_input.shape)
print(test_output.shape)

(100, 7)
(20, 7)
(100, 4)
(100, 3)
(20, 4)
(20, 3)


In [0]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import matplotlib.pyplot as plt

In [0]:
model = keras.Sequential([
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(3, activation='softmax')
])

In [0]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [0]:
model.fit(train_input, train_output, epochs=10)

Epoch 1/10
100/100 [==============================] - 0s 132us/sample - loss: 0.1916 - acc: 0.9700
Epoch 2/10
100/100 [==============================] - 0s 77us/sample - loss: 0.1908 - acc: 0.9700
Epoch 3/10
100/100 [==============================] - 0s 80us/sample - loss: 0.1905 - acc: 0.9700
Epoch 4/10
100/100 [==============================] - 0s 73us/sample - loss: 0.1878 - acc: 0.9600
Epoch 5/10
100/100 [==============================] - 0s 98us/sample - loss: 0.1861 - acc: 0.9700
Epoch 6/10
100/100 [==============================] - 0s 100us/sample - loss: 0.1854 - acc: 0.9700
Epoch 7/10
100/100 [==============================] - 0s 92us/sample - loss: 0.1841 - acc: 0.9700
Epoch 8/10
100/100 [==============================] - 0s 90us/sample - loss: 0.1825 - acc: 0.9700
Epoch 9/10
100/100 [==============================] - 0s 87us/sample - loss: 0.1813 - acc: 0.9700
Epoch 10/10
100/100 [==============================] - 0s 95us/sample - loss: 0.1827 - acc: 0.9600


In [0]:
test_loss, test_acc = model.evaluate(test_input, test_output)

print("test_loss :", test_loss)
print("test_acc :", test_acc)


20/20 [==============================] - 0s 1ms/sample - loss: 0.0984 - acc: 1.0000
test_loss : 0.09835753589868546
test_acc : 1.0


In [0]:
test_prediction = model.predict(test_input)
print(test_prediction)
print(np.argmax(test_prediction, axis=1))

[[9.85690653e-01 1.30305002e-02 1.27877016e-03]
 [4.91744094e-02 8.41030717e-01 1.09794855e-01]
 [9.42748904e-01 5.15238605e-02 5.72719099e-03]
 [2.45031212e-02 8.77072215e-01 9.84246507e-02]
 [9.82676923e-01 1.58111770e-02 1.51182909e-03]
 [9.93531525e-01 5.92408748e-03 5.44496754e-04]
 [9.95485485e-01 4.14847536e-03 3.65998480e-04]
 [9.95148599e-01 4.42059012e-03 4.30902583e-04]
 [3.38514596e-02 8.44347358e-01 1.21801212e-01]
 [9.81614888e-01 1.67711638e-02 1.61392184e-03]
 [2.36458349e-04 2.44538978e-01 7.55224586e-01]
 [1.09420363e-02 7.76585042e-01 2.12472916e-01]
 [9.79464591e-01 1.88219659e-02 1.71341957e-03]
 [3.63094614e-06 3.33414599e-02 9.66654897e-01]
 [9.75441992e-01 2.23363563e-02 2.22165859e-03]
 [5.87891648e-03 6.73443496e-01 3.20677668e-01]
 [1.80046298e-02 8.41725290e-01 1.40270084e-01]
 [9.80069399e-01 1.79315191e-02 1.99910486e-03]
 [9.88647878e-01 1.03301471e-02 1.02196261e-03]
 [2.73047742e-02 8.55498075e-01 1.17197059e-01]]
[0 1 0 1 0 0 0 0 1 0 2 1 0 2 0 1 1 0 0 

# Optimzer

- 'SGD' or tf.keras.optimizers.SGD()
- 'Adam' or tf.keras.optimizers.Adam()
- 'Adagrad' or tf.keras.optimizers.Adagrad()
- 'RMSprop' or tf.keras.optimizers.RMSprop()


```
SGD(lr=0.001)
Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-07)
Adagrad(lr=0.001, epsilon=1e-06)
RMSprop(lr=0.001, rho=0.9, decay=0.9)
```






In [0]:
def train(optimizer, loss, epochs=10):
  
  model = keras.Sequential([
      keras.layers.Dense(10, activation='relu'),
      keras.layers.Dense(10, activation='relu'),
      keras.layers.Dense(3, activation='softmax')
  ])

  model.compile(optimizer=optimizer,
                loss=loss,
                metrics=['accuracy'])

  model.fit(train_input, train_output, epochs=epochs)

  test_loss, test_acc = model.evaluate(test_input, test_output)

  print("test_loss :", test_loss)
  print("test_acc :", test_acc)


## optimizer - SGD

In [40]:
optimizer = "SGD"
loss = "categorical_crossentropy"

train(optimizer, loss, 10)

Epoch 1/10
100/100 [==============================] - 0s 2ms/sample - loss: 1.0555 - acc: 0.3900
Epoch 2/10
100/100 [==============================] - 0s 146us/sample - loss: 0.9820 - acc: 0.6900
Epoch 3/10
100/100 [==============================] - 0s 119us/sample - loss: 0.9574 - acc: 0.5000
Epoch 4/10
100/100 [==============================] - 0s 133us/sample - loss: 0.9663 - acc: 0.4800
Epoch 5/10
100/100 [==============================] - 0s 145us/sample - loss: 0.9457 - acc: 0.4200
Epoch 6/10
100/100 [==============================] - 0s 133us/sample - loss: 0.9186 - acc: 0.6600
Epoch 7/10
100/100 [==============================] - 0s 128us/sample - loss: 0.9134 - acc: 0.5200
Epoch 8/10
100/100 [==============================] - 0s 137us/sample - loss: 0.8861 - acc: 0.7100
Epoch 9/10
100/100 [==============================] - 0s 113us/sample - loss: 0.8759 - acc: 0.7000
Epoch 10/10
20/20 [==============================] - 0s 9ms/sample - loss: 0.9163 - acc: 0.6500
test_loss : 0.9

In [24]:
optimizer = tf.keras.optimizers.SGD(lr=0.01)
loss = "categorical_crossentropy"

train(optimizer, loss, 10)

Epoch 1/10
100/100 [==============================] - 0s 1ms/sample - loss: 2.5188 - acc: 0.2900
Epoch 2/10
100/100 [==============================] - 0s 97us/sample - loss: 1.5764 - acc: 0.3200
Epoch 3/10
100/100 [==============================] - 0s 98us/sample - loss: 1.3093 - acc: 0.3200
Epoch 4/10
100/100 [==============================] - 0s 94us/sample - loss: 1.1803 - acc: 0.3300
Epoch 5/10
100/100 [==============================] - 0s 99us/sample - loss: 1.0988 - acc: 0.4400
Epoch 6/10
100/100 [==============================] - 0s 85us/sample - loss: 1.0953 - acc: 0.2500
Epoch 7/10
100/100 [==============================] - 0s 95us/sample - loss: 1.0460 - acc: 0.4000
Epoch 8/10
100/100 [==============================] - 0s 91us/sample - loss: 1.0377 - acc: 0.4000
Epoch 9/10
100/100 [==============================] - 0s 76us/sample - loss: 1.0282 - acc: 0.4000
Epoch 10/10
20/20 [==============================] - 0s 5ms/sample - loss: 1.1373 - acc: 0.1000
test_loss : 1.137331247

## optimizer - Adam

In [36]:
optimizer = "Adam"
loss = "categorical_crossentropy"

train(optimizer, loss, 10)

Epoch 1/10
100/100 [==============================] - 0s 2ms/sample - loss: 1.8321 - acc: 0.3100
Epoch 2/10
100/100 [==============================] - 0s 129us/sample - loss: 1.7039 - acc: 0.3100
Epoch 3/10
100/100 [==============================] - 0s 175us/sample - loss: 1.5943 - acc: 0.3100
Epoch 4/10
100/100 [==============================] - 0s 132us/sample - loss: 1.4940 - acc: 0.3100
Epoch 5/10
100/100 [==============================] - 0s 118us/sample - loss: 1.3951 - acc: 0.3100
Epoch 6/10
100/100 [==============================] - 0s 132us/sample - loss: 1.3241 - acc: 0.3100
Epoch 7/10
100/100 [==============================] - 0s 126us/sample - loss: 1.2648 - acc: 0.3100
Epoch 8/10
100/100 [==============================] - 0s 135us/sample - loss: 1.2145 - acc: 0.3100
Epoch 9/10
100/100 [==============================] - 0s 134us/sample - loss: 1.1716 - acc: 0.3100
Epoch 10/10
20/20 [==============================] - 0s 8ms/sample - loss: 1.0907 - acc: 0.5500
test_loss : 1.0

In [41]:
optimizer = tf.keras.optimizers.Adam(lr=0.01, beta_1=0.9, beta_2=0.999, epsilon=1e-07)
loss = "categorical_crossentropy"

train(optimizer, loss, 10)

Epoch 1/10
100/100 [==============================] - 0s 3ms/sample - loss: 1.3724 - acc: 0.3300
Epoch 2/10
100/100 [==============================] - 0s 122us/sample - loss: 0.9039 - acc: 0.6300
Epoch 3/10
100/100 [==============================] - 0s 113us/sample - loss: 0.8203 - acc: 0.4800
Epoch 4/10
100/100 [==============================] - 0s 113us/sample - loss: 0.7536 - acc: 0.6500
Epoch 5/10
100/100 [==============================] - 0s 132us/sample - loss: 0.6288 - acc: 0.9700
Epoch 6/10
100/100 [==============================] - 0s 132us/sample - loss: 0.5219 - acc: 0.8100
Epoch 7/10
100/100 [==============================] - 0s 122us/sample - loss: 0.4922 - acc: 0.7100
Epoch 8/10
100/100 [==============================] - 0s 128us/sample - loss: 0.4673 - acc: 0.7100
Epoch 9/10
100/100 [==============================] - 0s 137us/sample - loss: 0.4152 - acc: 0.8600
Epoch 10/10
20/20 [==============================] - 0s 9ms/sample - loss: 0.3010 - acc: 1.0000
test_loss : 0.3

In [14]:
optimizer = tf.keras.optimizers.Adagrad(lr=0.01, epsilon=1e-06)
loss = "categorical_crossentropy"

train(optimizer, loss, 10)

W0721 15:15:46.057992 140064349947776 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/optimizer_v2/adagrad.py:105: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


Epoch 1/10
100/100 [==============================] - 0s 745us/sample - loss: 1.2594 - acc: 0.0000e+00
Epoch 2/10
100/100 [==============================] - 0s 91us/sample - loss: 1.1861 - acc: 0.0000e+00
Epoch 3/10
100/100 [==============================] - 0s 87us/sample - loss: 1.1486 - acc: 0.0000e+00
Epoch 4/10
100/100 [==============================] - 0s 107us/sample - loss: 1.1298 - acc: 0.0000e+00
Epoch 5/10
100/100 [==============================] - 0s 85us/sample - loss: 1.1131 - acc: 0.0400
Epoch 6/10
100/100 [==============================] - 0s 120us/sample - loss: 1.1015 - acc: 0.3300
Epoch 7/10
100/100 [==============================] - 0s 98us/sample - loss: 1.0915 - acc: 0.4200
Epoch 8/10
100/100 [==============================] - 0s 90us/sample - loss: 1.0834 - acc: 0.4600
Epoch 9/10
100/100 [==============================] - 0s 90us/sample - loss: 1.0753 - acc: 0.4000
Epoch 10/10
20/20 [==============================] - 0s 2ms/sample - loss: 1.1268 - acc: 0.2500
tes

In [17]:
optimizer = tf.keras.optimizers.RMSprop(lr=0.01, rho=0.9, decay=0.9)
loss = "categorical_crossentropy"

train(optimizer, loss, 10)

Epoch 1/10
100/100 [==============================] - 0s 1ms/sample - loss: 1.0707 - acc: 0.4700
Epoch 2/10
100/100 [==============================] - 0s 105us/sample - loss: 0.8156 - acc: 0.6200
Epoch 3/10
100/100 [==============================] - 0s 82us/sample - loss: 0.7749 - acc: 0.7000
Epoch 4/10
100/100 [==============================] - 0s 114us/sample - loss: 0.7567 - acc: 0.7100
Epoch 5/10
100/100 [==============================] - 0s 81us/sample - loss: 0.7475 - acc: 0.7000
Epoch 6/10
100/100 [==============================] - 0s 90us/sample - loss: 0.7373 - acc: 0.7100
Epoch 7/10
100/100 [==============================] - 0s 100us/sample - loss: 0.7311 - acc: 0.7100
Epoch 8/10
100/100 [==============================] - 0s 112us/sample - loss: 0.7253 - acc: 0.7000
Epoch 9/10
100/100 [==============================] - 0s 87us/sample - loss: 0.7204 - acc: 0.7100
Epoch 10/10
20/20 [==============================] - 0s 3ms/sample - loss: 0.6703 - acc: 0.6500
test_loss : 0.67033