# Quiz.
```
[ 0 1 2 0 1 2 0 1 2] 배열을

[ 1 0 0 ]
[ 0 1 0 ]
[ 0 0 1 ]
[ 0 0 0 ]
[ 0 1 0 ]
[ 0 0 1 ]
[ 1 0 0 ]
[ 0 1 0 ]
[ 0 0 1 ]
[ 0 0 0 ]
배열로 변환
```


In [1]:
import numpy as np

a = np.array([0,1,2,0,1,2,0,1,2])
b = np.zeros((a.shape[0],3))

# b[:,0] = (a==0)*1.0
# b[:,1] = (a==1)*1.0
# b[:,2] = (a==2)*1.0
for i in range(3):
  b[:,i] = (a==i)*1.0
  
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
import tensorflow.keras.utils

a = np.array([0,1,2,0,1,2,0,1,2])
b = tensorflow.keras.utils.to_categorical(a)

print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Quiz. 

임의의 데이터를 6:4로 나눈다.

[1 2 3 4 ... 9 0]을
[ 1 2 .. 6], [ 7 8 .. 0]으로 나눈다.


In [4]:
a = np.array([1,2,3,4,5,6,7,8,9,0])

split_index = int(a.shape[0]*0.6)

b1 = a[0:split_index]
b2 = a[split_index:]

print(b1)
print(b2)

[1 2 3 4 5 6]
[7 8 9 0]


# Quiz. 

임의의 데이터를 6:4로 나눈다.
```
[ 1 0 0 ]
[ 2 0 0 ]
...
[ 0 0 0 ]를

[ 1 0 0 ]
...
[ 6 0 0 ]와

[ 7 0 0 ]
...
[ 0 0 0 ]
```

In [9]:
a = np.zeros((10,3))
a[:,0] = [1,2,3,4,5,6,7,8,9,0]


split_index = int(a.shape[0]*0.6)

b1 = a[0:split_index]
b2 = a[split_index:]

print(b1)
print(b2)


[[1. 0. 0.]
 [2. 0. 0.]
 [3. 0. 0.]
 [4. 0. 0.]
 [5. 0. 0.]
 [6. 0. 0.]]
[[7. 0. 0.]
 [8. 0. 0.]
 [9. 0. 0.]
 [0. 0. 0.]]
