# loss categorical_crossentropy

2개의 사용 방법 

- categorical_crossentropy
- sparse_categorical_crossentropy

## categorical_crossentropy

y의 값이 one hot encoding인 경우

```
1,0,0
0,1,0
0,0,1
```

출력 레이어 설정
```
model.add(Dense(3)) # 출력 레이어
```

loss 설정
```
model.compile(..., loss='categorical_crossentropy')
```


## sparse_categorical_crossentropy

y의 값이 숫자 하나이며, category index 인 경우

```
0
1
2
```

출력 레이어 설정
```
model.add(Dense(3)) # 출력 레이어. 1 이 아니라 3으로 설정
```

loss 설정
```
model.compile(..., loss='sparse_categorical_crossentropy')
```







# iris_dnn with category index

아래의 코드는 iris_dnn_and_optimizer.ipynb의 코드를 기반으로 한다.

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import optimizers
from tensorflow.keras.layers import Dense

In [0]:
#!wget https://raw.githubusercontent.com/dhrim/cup_deeplearning_seminar/master/%EA%B5%90%EC%9C%A1%EC%9E%90%EB%A3%8C/deep_learning/iris.csv
!wget https://raw.githubusercontent.com/dhrim/cup_deeplearning_seminar/master/%EA%B5%90%EC%9C%A1%EC%9E%90%EB%A3%8C/deep_learning/iris_dnn_with_category_index.csv

--2019-07-22 11:52:57--  https://raw.githubusercontent.com/dhrim/cup_deeplearning_seminar/master/%EA%B5%90%EC%9C%A1%EC%9E%90%EB%A3%8C/deep_learning/iris.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2720 (2.7K) [text/plain]
Saving to: ‘iris.csv’

iris.csv            100%[===================>]   2.66K  --.-KB/s    in 0s      

2019-07-22 11:52:57 (59.9 MB/s) - ‘iris.csv’ saved [2720/2720]



In [0]:
#iris = pd.read_csv("iris.csv")
iris = pd.read_csv("iris_with_category_index.csv")
iris.head()

septal_length  septal_width  petal_length  petal_width  class
0            6.4           2.8           5.6          2.2      2
1            5.0           2.3           3.3          1.0      1
2            4.9           2.5           4.5          1.7      2
3            4.9           3.1           1.5          0.1      0
4            5.7           3.8           1.7          0.3      0

In [0]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
septal_length    120 non-null float64
septal_width     120 non-null float64
petal_length     120 non-null float64
petal_width      120 non-null float64
setosa           120 non-null int64
versicolor       120 non-null int64
virginica        120 non-null int64
dtypes: float64(4), int64(3)
memory usage: 6.6 KB


In [0]:
data = iris.to_numpy()
print(data.shape)
print(data[:5])

(120, 5)
[[6.4 2.8 5.6 2.2 2. ]
 [5.  2.3 3.3 1.  1. ]
 [4.9 2.5 4.5 1.7 2. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.7 3.8 1.7 0.3 0. ]]


In [0]:
x = data[:,:4]
y = data[:,4:]
#y = data[:,4]

split_index = 100

train_x, test_x = x[:split_index], x[split_index:]
train_y, test_y = y[:split_index], y[split_index:]

In [0]:
model = keras.Sequential([
    keras.layers.Dense(10, activation='relu', input_shape=(train_x.shape[1],)),
    keras.layers.Dense(10, activation='relu'),
#    keras.layers.Dense(train_y.shape[1], activation='softmax')
    keras.layers.Dense(3, activation='softmax')
])

W0722 12:35:19.378892 139724613220224 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [0]:
model.compile(optimizer='adam',
#               loss='categorical_crossentropy',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [0]:
model.fit(train_x, train_y, epochs=200, verbose=0)

In [0]:
loss, acc = model.evaluate(test_x, test_y)

print("loss :", loss)
print("acc :", acc)


20/20 [==============================] - 0s 75us/sample - loss: 0.2224 - acc: 1.0000
loss : 0.222386434674263
acc : 1.0


In [0]:
y_ = model.predict(test_x)
print(y_)
print(np.argmax(y_, axis=1))

[[9.83112037e-01 1.21990135e-02 4.68893023e-03]
 [3.51981446e-02 6.53293073e-01 3.11508745e-01]
 [9.56817687e-01 3.17955725e-02 1.13868117e-02]
 [1.18341278e-02 6.41884029e-01 3.46281856e-01]
 [9.83308613e-01 1.23865549e-02 4.30476945e-03]
 [9.90568697e-01 6.73002610e-03 2.70135887e-03]
 [9.92695689e-01 5.22216875e-03 2.08212901e-03]
 [9.91470516e-01 6.07919227e-03 2.45022168e-03]
 [2.79240329e-02 6.54778779e-01 3.17297161e-01]
 [9.79820192e-01 1.48314172e-02 5.34841465e-03]
 [4.87401674e-04 4.60171938e-01 5.39340675e-01]
 [7.57463276e-03 6.16679013e-01 3.75746369e-01]
 [9.79911625e-01 1.47526432e-02 5.33569045e-03]
 [3.53508003e-05 3.35786790e-01 6.64177895e-01]
 [9.81027365e-01 1.42981410e-02 4.67454782e-03]
 [3.77878919e-03 5.76549470e-01 4.19671744e-01]
 [1.07322903e-02 6.43777132e-01 3.45490515e-01]
 [9.75427806e-01 1.79068893e-02 6.66528894e-03]
 [9.84111965e-01 1.13834459e-02 4.50456794e-03]
 [1.50933964e-02 6.37648165e-01 3.47258419e-01]]
[0 1 0 1 0 0 0 0 1 0 2 1 0 2 0 1 1 0 0 