In [0]:
import csv
import numpy as np
import pandas as pd

In [40]:
iris = pd.read_csv("iris.csv")
iris.head()

septal_length  septal_width  petal_length  ...  setosa  versicolor  virginica
0            6.4           2.8           5.6  ...       0           0          1
1            5.0           2.3           3.3  ...       0           1          0
2            4.9           2.5           4.5  ...       0           0          1
3            4.9           3.1           1.5  ...       1           0          0
4            5.7           3.8           1.7  ...       1           0          0

[5 rows x 7 columns]

In [42]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
septal_length    120 non-null float64
septal_width     120 non-null float64
petal_length     120 non-null float64
petal_width      120 non-null float64
setosa           120 non-null int64
versicolor       120 non-null int64
virginica        120 non-null int64
dtypes: float64(4), int64(3)
memory usage: 6.6 KB


In [50]:
data = iris.to_numpy()
print(data.shape)
print(data[:5])

(120, 7)
[[6.4 2.8 5.6 2.2 0.  0.  1. ]
 [5.  2.3 3.3 1.  0.  1.  0. ]
 [4.9 2.5 4.5 1.7 0.  0.  1. ]
 [4.9 3.1 1.5 0.1 1.  0.  0. ]
 [5.7 3.8 1.7 0.3 1.  0.  0. ]]


In [48]:
train, test = data[:100], data[100:]
print(train.shape)
print(test.shape)

train_input, train_output = train[:,:4], train[:,4:]
test_input, test_output = test[:,:4], test[:,4:]

print(train_input.shape)
print(train_output.shape)

print(test_input.shape)
print(test_output.shape)

(100, 7)
(20, 7)
(100, 4)
(100, 3)
(20, 4)
(20, 3)


In [0]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import matplotlib.pyplot as plt

In [0]:
model = keras.Sequential([
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(3, activation='softmax')
])

In [0]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [65]:
model.fit(train_input, train_output, epochs=10)

Epoch 1/10
100/100 [==============================] - 0s 132us/sample - loss: 0.1916 - acc: 0.9700
Epoch 2/10
100/100 [==============================] - 0s 77us/sample - loss: 0.1908 - acc: 0.9700
Epoch 3/10
100/100 [==============================] - 0s 80us/sample - loss: 0.1905 - acc: 0.9700
Epoch 4/10
100/100 [==============================] - 0s 73us/sample - loss: 0.1878 - acc: 0.9600
Epoch 5/10
100/100 [==============================] - 0s 98us/sample - loss: 0.1861 - acc: 0.9700
Epoch 6/10
100/100 [==============================] - 0s 100us/sample - loss: 0.1854 - acc: 0.9700
Epoch 7/10
100/100 [==============================] - 0s 92us/sample - loss: 0.1841 - acc: 0.9700
Epoch 8/10
100/100 [==============================] - 0s 90us/sample - loss: 0.1825 - acc: 0.9700
Epoch 9/10
100/100 [==============================] - 0s 87us/sample - loss: 0.1813 - acc: 0.9700
Epoch 10/10
100/100 [==============================] - 0s 95us/sample - loss: 0.1827 - acc: 0.9600


In [67]:
test_loss, test_acc = model.evaluate(test_input, test_output)

print("test_loss :", test_loss)
print("test_acc :", test_acc)


20/20 [==============================] - 0s 1ms/sample - loss: 0.0984 - acc: 1.0000
test_loss : 0.09835753589868546
test_acc : 1.0


In [71]:
test_prediction = model.predict(test_input)
print(test_prediction)
print(np.argmax(test_prediction, axis=1))

[[9.85690653e-01 1.30305002e-02 1.27877016e-03]
 [4.91744094e-02 8.41030717e-01 1.09794855e-01]
 [9.42748904e-01 5.15238605e-02 5.72719099e-03]
 [2.45031212e-02 8.77072215e-01 9.84246507e-02]
 [9.82676923e-01 1.58111770e-02 1.51182909e-03]
 [9.93531525e-01 5.92408748e-03 5.44496754e-04]
 [9.95485485e-01 4.14847536e-03 3.65998480e-04]
 [9.95148599e-01 4.42059012e-03 4.30902583e-04]
 [3.38514596e-02 8.44347358e-01 1.21801212e-01]
 [9.81614888e-01 1.67711638e-02 1.61392184e-03]
 [2.36458349e-04 2.44538978e-01 7.55224586e-01]
 [1.09420363e-02 7.76585042e-01 2.12472916e-01]
 [9.79464591e-01 1.88219659e-02 1.71341957e-03]
 [3.63094614e-06 3.33414599e-02 9.66654897e-01]
 [9.75441992e-01 2.23363563e-02 2.22165859e-03]
 [5.87891648e-03 6.73443496e-01 3.20677668e-01]
 [1.80046298e-02 8.41725290e-01 1.40270084e-01]
 [9.80069399e-01 1.79315191e-02 1.99910486e-03]
 [9.88647878e-01 1.03301471e-02 1.02196261e-03]
 [2.73047742e-02 8.55498075e-01 1.17197059e-01]]
[0 1 0 1 0 0 0 0 1 0 2 1 0 2 0 1 1 0 0 