In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import optimizers
from tensorflow.keras.layers import Dense

In [0]:
!wget https://raw.githubusercontent.com/dhrim/cup_deeplearning_seminar/master/%EA%B5%90%EC%9C%A1%EC%9E%90%EB%A3%8C/deep_learning/iris.csv

--2019-07-22 11:52:57--  https://raw.githubusercontent.com/dhrim/cup_deeplearning_seminar/master/%EA%B5%90%EC%9C%A1%EC%9E%90%EB%A3%8C/deep_learning/iris.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2720 (2.7K) [text/plain]
Saving to: ‘iris.csv’

iris.csv            100%[===================>]   2.66K  --.-KB/s    in 0s      

2019-07-22 11:52:57 (59.9 MB/s) - ‘iris.csv’ saved [2720/2720]



In [0]:
iris = pd.read_csv("iris.csv")
iris.head()

septal_length  septal_width  petal_length  ...  setosa  versicolor  virginica
0            6.4           2.8           5.6  ...       0           0          1
1            5.0           2.3           3.3  ...       0           1          0
2            4.9           2.5           4.5  ...       0           0          1
3            4.9           3.1           1.5  ...       1           0          0
4            5.7           3.8           1.7  ...       1           0          0

[5 rows x 7 columns]

In [0]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
septal_length    120 non-null float64
septal_width     120 non-null float64
petal_length     120 non-null float64
petal_width      120 non-null float64
setosa           120 non-null int64
versicolor       120 non-null int64
virginica        120 non-null int64
dtypes: float64(4), int64(3)
memory usage: 6.6 KB


In [0]:
data = iris.to_numpy()
print(data.shape)
print(data[:5])

(120, 7)
[[6.4 2.8 5.6 2.2 0.  0.  1. ]
 [5.  2.3 3.3 1.  0.  1.  0. ]
 [4.9 2.5 4.5 1.7 0.  0.  1. ]
 [4.9 3.1 1.5 0.1 1.  0.  0. ]
 [5.7 3.8 1.7 0.3 1.  0.  0. ]]


In [0]:
x = data[:,:4]
y = data[:,4:]

split_index = 100

train_x, test_x = x[:split_index], x[split_index:]
train_y, test_y = y[:split_index], y[split_index:]

In [0]:
model = keras.Sequential([
    keras.layers.Dense(10, activation='relu', input_shape=(train_x.shape[1],)),
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(train_y.shape[1], activation='softmax')
])

In [0]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [0]:
model.fit(train_x, train_y, epochs=200, verbose=0)

In [0]:
loss, acc = model.evaluate(test_x, test_y)

print("loss :", loss)
print("acc :", acc)


20/20 [==============================] - 0s 180us/sample - loss: 0.2087 - acc: 1.0000
loss : 0.20874568819999695
acc : 1.0


In [0]:
y_ = model.predict(test_x)
print(y_)
print(np.argmax(y_, axis=1))

[[9.5934635e-01 4.0229280e-02 4.2442654e-04]
 [9.3170352e-02 6.6391361e-01 2.4291605e-01]
 [9.1371399e-01 8.4611416e-02 1.6745505e-03]
 [4.5848995e-02 7.0195627e-01 2.5219467e-01]
 [9.4871980e-01 5.0555121e-02 7.2511053e-04]
 [9.6779346e-01 3.1962518e-02 2.4399521e-04]
 [9.7017729e-01 2.9602863e-02 2.1990167e-04]
 [9.6535349e-01 3.4321785e-02 3.2473583e-04]
 [7.1442954e-02 6.8595731e-01 2.4259977e-01]
 [9.4780815e-01 5.1459871e-02 7.3201093e-04]
 [1.8324244e-03 3.5613698e-01 6.4203054e-01]
 [2.5649322e-02 6.1223996e-01 3.6211076e-01]
 [9.4642758e-01 5.2929152e-02 6.4314855e-04]
 [2.8999939e-05 6.4928144e-02 9.3504286e-01]
 [9.3536097e-01 6.3459702e-02 1.1793859e-03]
 [1.1778355e-02 5.1212680e-01 4.7609481e-01]
 [3.1942356e-02 6.2877226e-01 3.3928540e-01]
 [9.4823027e-01 5.0878275e-02 8.9150609e-04]
 [9.6014363e-01 3.9455928e-02 4.0032656e-04]
 [6.1469343e-02 7.0579487e-01 2.3273575e-01]]
[0 1 0 1 0 0 0 0 1 0 2 1 0 2 0 1 1 0 0 1]


# Optimzer

- 'SGD' or tf.keras.optimizers.SGD()
- 'Adam' or tf.keras.optimizers.Adam()
- 'Adagrad' or tf.keras.optimizers.Adagrad()
- 'RMSprop' or tf.keras.optimizers.RMSprop()


```
SGD(lr=0.001)
Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-07)
Adagrad(lr=0.001, epsilon=1e-06)
RMSprop(lr=0.001, rho=0.9, decay=0.9)
```






In [0]:
def train(optimizer, loss, epochs=10):
  
  model = keras.Sequential([
      keras.layers.Dense(10, activation='relu'),
      keras.layers.Dense(10, activation='relu'),
      keras.layers.Dense(3, activation='softmax')
  ])

  model.compile(optimizer=optimizer,
                loss=loss,
                metrics=['accuracy'])

  model.fit(train_x, train_y, epochs=epochs)

  loss, acc = model.evaluate(test_x, test_y)

  print("loss :", loss)
  print("acc :", acc)


## optimizer - SGD

In [0]:
optimizer = "SGD"
loss = "categorical_crossentropy"

train(optimizer, loss, 10)

Epoch 1/10
100/100 [==============================] - 0s 526us/sample - loss: 1.9635 - acc: 0.3100
Epoch 2/10
100/100 [==============================] - 0s 92us/sample - loss: 0.8568 - acc: 0.5900
Epoch 3/10
100/100 [==============================] - 0s 106us/sample - loss: 0.7941 - acc: 0.8800
Epoch 4/10
100/100 [==============================] - 0s 123us/sample - loss: 0.7820 - acc: 0.9100
Epoch 5/10
100/100 [==============================] - 0s 105us/sample - loss: 0.7720 - acc: 0.8300
Epoch 6/10
100/100 [==============================] - 0s 102us/sample - loss: 0.7647 - acc: 0.8200
Epoch 7/10
100/100 [==============================] - 0s 196us/sample - loss: 0.7556 - acc: 0.8900
Epoch 8/10
100/100 [==============================] - 0s 104us/sample - loss: 0.7491 - acc: 0.8400
Epoch 9/10
100/100 [==============================] - 0s 117us/sample - loss: 0.7435 - acc: 0.9000
Epoch 10/10
20/20 [==============================] - 0s 1ms/sample - loss: 0.5188 - acc: 0.8500
loss : 0.51876

In [0]:
optimizer = tf.keras.optimizers.SGD(lr=0.01)
loss = "categorical_crossentropy"

train(optimizer, loss, 10)

Epoch 1/10
100/100 [==============================] - 0s 537us/sample - loss: 3.4895 - acc: 0.2900
Epoch 2/10
100/100 [==============================] - 0s 192us/sample - loss: 1.6425 - acc: 0.2900
Epoch 3/10
100/100 [==============================] - 0s 147us/sample - loss: 1.3700 - acc: 0.2900
Epoch 4/10
100/100 [==============================] - 0s 99us/sample - loss: 1.1276 - acc: 0.4000
Epoch 5/10
100/100 [==============================] - 0s 91us/sample - loss: 1.0648 - acc: 0.3800
Epoch 6/10
100/100 [==============================] - 0s 112us/sample - loss: 1.0382 - acc: 0.4000
Epoch 7/10
100/100 [==============================] - 0s 96us/sample - loss: 1.0211 - acc: 0.4000
Epoch 8/10
100/100 [==============================] - 0s 104us/sample - loss: 1.0149 - acc: 0.4000
Epoch 9/10
100/100 [==============================] - 0s 112us/sample - loss: 1.0092 - acc: 0.4000
Epoch 10/10
20/20 [==============================] - 0s 2ms/sample - loss: 1.0961 - acc: 0.1500
loss : 1.0961009

## optimizer - Adam

In [0]:
optimizer = "Adam"
loss = "categorical_crossentropy"

train(optimizer, loss, 10)

Epoch 1/10
100/100 [==============================] - 0s 842us/sample - loss: 0.9752 - acc: 0.4000
Epoch 2/10
100/100 [==============================] - 0s 126us/sample - loss: 0.9416 - acc: 0.4000
Epoch 3/10
100/100 [==============================] - 0s 124us/sample - loss: 0.9126 - acc: 0.4000
Epoch 4/10
100/100 [==============================] - 0s 117us/sample - loss: 0.8839 - acc: 0.4000
Epoch 5/10
100/100 [==============================] - 0s 115us/sample - loss: 0.8631 - acc: 0.4000
Epoch 6/10
100/100 [==============================] - 0s 156us/sample - loss: 0.8435 - acc: 0.4000
Epoch 7/10
100/100 [==============================] - 0s 114us/sample - loss: 0.8261 - acc: 0.4000
Epoch 8/10
100/100 [==============================] - 0s 124us/sample - loss: 0.8096 - acc: 0.4000
Epoch 9/10
100/100 [==============================] - 0s 126us/sample - loss: 0.7936 - acc: 0.6200
Epoch 10/10
20/20 [==============================] - 0s 2ms/sample - loss: 1.0001 - acc: 0.6500
loss : 1.0001

In [0]:
optimizer = tf.keras.optimizers.Adam(lr=0.01, beta_1=0.9, beta_2=0.999, epsilon=1e-07)
loss = "categorical_crossentropy"

train(optimizer, loss, 10)

Epoch 1/10
100/100 [==============================] - 0s 845us/sample - loss: 2.7961 - acc: 0.3100
Epoch 2/10
100/100 [==============================] - 0s 85us/sample - loss: 1.2273 - acc: 0.3400
Epoch 3/10
100/100 [==============================] - 0s 87us/sample - loss: 1.0475 - acc: 0.2900
Epoch 4/10
100/100 [==============================] - 0s 135us/sample - loss: 0.9624 - acc: 0.3100
Epoch 5/10
100/100 [==============================] - 0s 107us/sample - loss: 0.8140 - acc: 0.5700
Epoch 6/10
100/100 [==============================] - 0s 98us/sample - loss: 0.6927 - acc: 0.7100
Epoch 7/10
100/100 [==============================] - 0s 99us/sample - loss: 0.6350 - acc: 0.7100
Epoch 8/10
100/100 [==============================] - 0s 89us/sample - loss: 0.5763 - acc: 0.7100
Epoch 9/10
100/100 [==============================] - 0s 88us/sample - loss: 0.5298 - acc: 0.7100
Epoch 10/10
20/20 [==============================] - 0s 2ms/sample - loss: 0.4807 - acc: 0.6500
loss : 0.4806707501

In [0]:
optimizer = tf.keras.optimizers.Adagrad(lr=0.01, epsilon=1e-06)
loss = "categorical_crossentropy"

train(optimizer, loss, 10)

W0722 12:00:19.237971 139985903482752 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/optimizer_v2/adagrad.py:105: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


Epoch 1/10
100/100 [==============================] - 0s 871us/sample - loss: 1.9206 - acc: 0.3100
Epoch 2/10
100/100 [==============================] - 0s 86us/sample - loss: 1.6465 - acc: 0.0300
Epoch 3/10
100/100 [==============================] - 0s 76us/sample - loss: 1.4907 - acc: 0.0100
Epoch 4/10
100/100 [==============================] - 0s 117us/sample - loss: 1.4023 - acc: 0.3900
Epoch 5/10
100/100 [==============================] - 0s 77us/sample - loss: 1.3220 - acc: 0.2500
Epoch 6/10
100/100 [==============================] - 0s 88us/sample - loss: 1.2698 - acc: 0.3100
Epoch 7/10
100/100 [==============================] - 0s 90us/sample - loss: 1.2222 - acc: 0.3800
Epoch 8/10
100/100 [==============================] - 0s 105us/sample - loss: 1.1824 - acc: 0.5500
Epoch 9/10
100/100 [==============================] - 0s 65us/sample - loss: 1.1520 - acc: 0.4400
Epoch 10/10
20/20 [==============================] - 0s 2ms/sample - loss: 1.1730 - acc: 0.1000
loss : 1.1729729175

In [0]:
optimizer = tf.keras.optimizers.RMSprop(lr=0.01, rho=0.9, decay=0.9)
loss = "categorical_crossentropy"

train(optimizer, loss, 10)

Epoch 1/10
100/100 [==============================] - 0s 1ms/sample - loss: 1.0161 - acc: 0.5300
Epoch 2/10
100/100 [==============================] - 0s 90us/sample - loss: 0.8675 - acc: 0.8500
Epoch 3/10
100/100 [==============================] - 0s 81us/sample - loss: 0.8359 - acc: 0.7300
Epoch 4/10
100/100 [==============================] - 0s 92us/sample - loss: 0.8212 - acc: 0.7200
Epoch 5/10
100/100 [==============================] - 0s 89us/sample - loss: 0.8133 - acc: 0.7200
Epoch 6/10
100/100 [==============================] - 0s 92us/sample - loss: 0.8062 - acc: 0.7200
Epoch 7/10
100/100 [==============================] - 0s 91us/sample - loss: 0.8005 - acc: 0.7200
Epoch 8/10
100/100 [==============================] - 0s 100us/sample - loss: 0.7973 - acc: 0.7300
Epoch 9/10
100/100 [==============================] - 0s 89us/sample - loss: 0.7915 - acc: 0.7200
Epoch 10/10
20/20 [==============================] - 0s 3ms/sample - loss: 0.8703 - acc: 0.7500
loss : 0.8702801465988